In [1]:
import pandas as pd

In [16]:
reviews_df= pd.read_csv("https://media.githubusercontent.com/media/david-adewoyin/apple_podcasts/main/dataset/user_reviews.csv",
                names=['id','podcast_id','username','review_title','review','rating','date'])
podcast_df = pd.read_csv("https://raw.githubusercontent.com/david-adewoyin/apple_podcasts/main/dataset/podcasts.csv",
                         names=['id','name','url','studio','category','episode_count','avg_rating','total_ratings','description'])

In [9]:
reviews_df.head()

,id,podcast_id,username,title,review,rating,date
0,1,id1647910854,bogwalks,DEJa Vu,It’s so amazing that this is deja vu. The stor...,5,2022-10-28
1,2,id1647910854,BlueIowan,…and the past repeats…,What a dizzying ride into the past as well as ...,5,2022-10-28
2,3,id1647910854,Pandora's Abyss,Thank you for bringing this to light!,I say this has happened and people look at me ...,5,2022-10-28
3,4,id1647910854,TMittels,Ultra Podcast,Crazy how history is repeating itself- just ch...,5,2022-10-28
4,5,id1647910854,Kristos Paras Kever,I love Rachel,But you can’t be wrong that many times and rem...,1,2022-10-28

In [22]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542285 entries, 0 to 542284
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            542285 non-null  int64
 1   podcast_id    542285 non-null  object
 2   username      542285 non-null  object
 3   review_title  542280 non-null  object
 4   review        542282 non-null  object
 5   rating        542285 non-null  int64
 6   date          542285 non-null  object
dtypes: int64(2), object(5)
memory usage: 29.0+ MB

In [21]:
podcast_df.head()

,id,name,url,studio,category,episode_count,avg_rating,total_ratings,description
0,id1647910854,Rachel Maddow Presents: Ultra,https://podcasts.apple.com/us/podcast/rachel-m...,MSNBC,News,5,4.8,14900,Sitting members of Congress aiding and abettin...
1,id1464919521,Dateline NBC,https://podcasts.apple.com/us/podcast/dateline...,Dateline NBC,True Crime,456,4.5,29000,"Current and classic episodes, featuring compel..."
2,id1200361736,The Daily,https://podcasts.apple.com/us/podcast/the-dail...,The New York Times,News,1669,4.4,88100,This is what the news should sound like. The b...
3,id1322200189,Crime Junkie,https://podcasts.apple.com/us/podcast/crime-ju...,audiochuck,True Crime,282,4.8,326400,If you can never get enough true crime... Cong...
4,id1379959217,Morbid,https://podcasts.apple.com/us/podcast/morbid/i...,Wondery,Comedy,447,4.5,76000,"It’s a lighthearted nightmare in here, weirdos..."

In [23]:
podcast_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             2363 non-null   object
 1   name           2363 non-null   object
 2   url            2363 non-null   object
 3   studio         924 non-null    object
 4   category       2363 non-null   object
 5   episode_count  2363 non-null   int64
 6   avg_rating     2363 non-null   float64
 7   total_ratings  2363 non-null   int64
 8   description    2363 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 166.3+ KB